### ISSUE TITLE
Status of OpenJDK and Oracle JDK builds with IS

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#607]
**Description:**
We need to determine what is the latest of IS 5.4.1 with OpenJDK and OracleJDK.

**Affected Product Version:**
0.9.0-m17

**OS, DB, other environment details and versions:**    
OpenJDK 8/9
OracleJDK 8/9

**Steps to reproduce:**
We need to run this with Harshan's cloudformation scripts.

**Related Issues:**
#565  #560

**Comment by pasindujw** [comment]
An Update: We had faced the issue #608 and being fixed successfully. Continuing on testing ATM with the new TestGrid deployment.

**Comment by pasindujw** [comment]
Update2: 
Received the following error when running for UBUNTU | ORACEL JDK 9 | MySQL 5.7
(The server was not starting up. Logged into the is-node and trying to manually start the server, received the following.)

```
 Starting WSO2 Carbon (in unsupported JDK)
 [ERROR] CARBON is supported only on JDK 1.7 and 1.8
JAVA_HOME environment variable is set to /usr/lib/jvm/java-9-oracle
CARBON_HOME environment variable is set to /opt/wso2/wso2is-5.4.0
Using Java memory options: -Xms256m -Xmx1024m
-Djava.endorsed.dirs=/opt/wso2/wso2is-5.4.0/lib/endorsed:/usr/lib/jvm/java-9-oracle/jre/lib/endorsed:/usr/lib/jvm/java-9-oracle/lib/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by pasindujw** [comment]
**wso2is-LTS status as at 22/03/2018**

Combination | Deployment | Status | Reason
-- | -- | -- | --
UBUNTU \| ORACEL JDK 9 \| MySQL 5.7 | Stack created.Infrastructure configured.Product deployed.Tests didn’t run | ERROR | WSO2-IS doesn’t starting up in JDK 9.Starting WSO2 Carbon (in unsupported JDK) [ERROR] CARBON is supported only on JDK 1.7 and 1.8Error: Could not create the Java Virtual Machine.Error: A fatal exception has occurred. Program will exit.
UBUNTU \| ORACEL JDK 8 \| MySQL 5.7 | Stack createdInfrastructure configured.Product deployed.Tests executed. | Fail | Tests are failing.(Jenkins Log: https://testgrid-live-dev.private.wso2.com/job/wso2is-5.4.1-LTS/148/console)Observe intermittant failures to start the product due to following; https://gist.github.com/pasindujw/67af1ace8baee6646af31087af15ca3f
UBUNTU \| OPEN JDK 9 \| MySQL 5.7 | Stack created.Infrastructure configured.Product deployed.Tests didn’t run | ERROR | WSO2-IS doesn’t starting up in JDK 9. (Similar to Oracle JDK9)(Refer: https://gist.github.com/pasindujw/5798eb1c726758ebe39f2801878eeab1 )
UBUNTU \| OPEN JDK 8 \| MySQL 5.7 | Stack createdInfrastructure configured.Product deployed.Tests executed. | Fail | Tests are failing (Jenkins Log: https://testgrid-live-dev.private.wso2.com/job/wso2is-5.4.1-LTS/149/console )
CentOS \| ORACEL JDK 9 \| MySQL 5.7 | Stack created.Infrastructure not configured properly. | ERROR | The workaround-CF-script written by TestGrid faced issues with CentOS due to using ubuntu-specific commands and user-name (“ubuntu”) in the scripts. The team will be looking into this.
CentOS \| ORACEL JDK 8 \| MySQL 5.7 | Stack created.Infrastructure not configured properly. | ERROR | The workaround-CF-script written by TestGrid faced issues with CentOS due to using ubuntu-specific commands and user-name (“ubuntu”) in the scripts. The team will be looking into this.
CentOS \| OpenJDK 9 \| MySQL 5.7 | Stack created.Infrastructure not configured properly. | ERROR | The workaround-CF-script written by TestGrid faced issues with CentOS due to using ubuntu-specific commands and user-name (“ubuntu”) in the scripts. The team will be looking into this.
CentOS \| OpenJDK 8 \| MySQL 5.7 | Stack created.Infrastructure not configured properly. | ERROR | The workaround-CF-script written by TestGrid faced issues with CentOS due to using ubuntu-specific commands and user-name (“ubuntu”) in the scripts. The team will be looking into this.
