### ISSUE TITLE
Testgrid dashboard does not show the log content

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#634]
**Description:**
All that need to be said is here in this location [1]:

![image](https://user-images.githubusercontent.com/936037/38086636-bbb6ef9a-3372-11e8-8e4f-23e70a44d682.png)

[1] https://testgrid-live.private.wso2.com/testgrid/dashboard/testplans/0e54473c-67d7-4991-97b4-7f6bde7fc6f4

**Affected Product Version:**
0.9.0-m18

**OS, DB, other environment details and versions:**    
Linux/Chrome

**Steps to reproduce:**
Combination: 
wso2is-5.4.1-LTS /default /{"JDK":"OPEN_JDK9","OS":"CentOS","DBEngineVersion":"5.7","DBEngine":"mysql"}
https://testgrid-live.private.wso2.com/testgrid/dashboard/testplans/0e54473c-67d7-4991-97b4-7f6bde7fc6f4

**Related Issues:**
N/A

**Comment by azinneera** [comment]
This has two reasons.
1. The log files are taken from the s3 bucket and the files are uploaded during the execution of the post block. Therefore, the logs will be available only after all the test-plans have completed executing.
_**This was fixed by uploading the log files after each test-plan execution.**_

2. If a build is forcibly terminated, the subsequent steps will be aborted and if the log files are yet to be uploaded this view will be experienced. To resolve this we would need an alternative like a cron job, in addition, to upload log files to the s3 console.

**Comment by azinneera** [comment]
> On #1 - We have had live logs. So, while the build is going on, the logs
> are fetched from the file system. After the build is completed, then the
> dashboard fetch it from S3. That's how it's supposed to work. :)

#312 should be able to resolve this. AFAIK, ELK stack already provides the capability for live logs.

> +1 for #2

We need to think of a way to scedule the cron job. The cron job should be run after every build and we have two options here.
1. Through a pipeline watching the build job 
2. A cron job as backgroud process

Option 1 - This too can be terminated by someone
Option 2 - Will avoid the drawback in the first option but how would the cron job know of the build completion?

**Comment by pasindujw** [comment]
This is fixed.
