### ISSUE TITLE
Get wso2is-5.5.0-LTS error % to zero

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#680]
**Description:**
Some testcases of IS scenario tests we run in Testgrid are failing for some reason. We need to find out from where the errors are coming and bring the error percentage to zero.

**Affected Product Version:**
0.9.0-m21

**OS, DB, other environment details and versions:**    
IS on all infrastructure combinations.

**Steps to reproduce:**

**Related Issues:**
#701

**Comment by harshanL** [comment]
I've added some issues [1] in the identity-test-integration repo for fixing and verifying test cases. Yet this has to be investigated in order to make it 100% as some scenarios work perfectly when ran using local JMeter. Some issues can be fixed by adding mapping to "is.qa.com" in /etc/hosts file.

[1]. https://github.com/wso2-incubator/identity-test-integration/issues

**Comment by kasunbg** [comment]
Sounds good. Are we automatically adding the mapping for "is.qa.com" into /etc/hosts?

As I see, these scenarios has issues: 01, 03, 09, 11, 12
Apart from these following scenarios cannot be run in testgrid due to config-changeset requirement.
[05, 14, 23](https://github.com/wso2-incubator/identity-test-integration/blob/master/WSO2Scenariofile.yaml#L92) 

Does this mean rest of the scenarios mentioned in [here](https://github.com/wso2-incubator/identity-test-integration/blob/master/WSO2Scenariofile.yaml) can be run?

Thanks,
KasunG

**Comment by harshanL** [comment]
For now, I've hardcoded it since QA-tomcat instance is a static one. When we start parallel test runs, we won't be able to stick to a single Tomcat. Thus, we need to come up with a plan to dynamically start QA instance and add it automatically as a part of QA scripts. Modifying /etc/hosts in the jenkins won't be a problem as we will have to spawn jenkins slave per build.

**Comment by harshanL** [comment]
This can be fixed with https://github.com/wso2/testgrid/issues/701.

**Comment by pasindujw** [comment]
Closing since the job is N/A
