### ISSUE TITLE
Get wso2apim-2.2.0-LTS error % to zero

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#682]
**Description:**
API-M build is reporting loads of issues. We need to bring the error percentage to zero to make testgrid ready for support requests.

**Affected Product Version:**
0.9.0-m21

**OS, DB, other environment details and versions:**    
AWS CFN
APIM 2.2.0
All infra combinations - We can focus on MySQL first.

**Steps to reproduce:**

**Related Issues:**
#680

**Comment by azinneera** [comment]
Looked into scenario03, 04 and 05 which were said to be completed but these are not ready to run on TestGrid yet. Issues have been raised for each and the reasons are as follows:

- **scenario03** - Missing pre and post scripts ( https://github.com/wso2-incubator/apim-test-integration/issues/27)
- **scenario04** - MSF4J service should be started before execution of the scenario. This has not been done in pre scenario script (https://github.com/wso2-incubator/apim-test-integration/issues/28)
- **scenario05** - Requires some configuration changes and deployment of GREG in APIM before scenario execution. These have to be fulfilled in the pre scenario script (https://github.com/wso2-incubator/apim-test-integration/issues/29)

**Comment by kasunbg** [comment]
OK, thanks. 

So, what's left as per [1] is the scenarios 01, 06, and 09. Scenario 01 cannot be run since it require a config-changeset. 

Therefore, we can only run 06, 09. Is that correct?

[1] https://github.com/wso2-incubator/apim-test-integration/blob/master/testgrid.yaml

Thanks,
KasunG

**Comment by azinneera** [comment]
[1] is not properly maintained and so we cannot run the scenarios that are there in [1]. 03, 04 and 05 are the only scenarios that were told to be complete. The update on these are as follows:

**scenario03** - Fixed errors in test scripts and the cf script. PR sent: https://github.com/wso2-incubator/apim-test-integration/pull/35

**scenario04** - Fixed errors in test scripts and the cf script. PR sent: https://github.com/wso2-incubator/apim-test-integration/pull/32
One test case is disabled due to the requirement of config changes in registry.xml. Related issue - https://github.com/wso2-incubator/apim-test-integration/issues/30

**scenario05** - Requires config changes

[1] https://github.com/wso2-incubator/apim-test-integration/blob/master/testgrid.yaml

**Comment by azinneera** [comment]
Since scenario05 is not testgrid ready yet, considering the completion of scenarios 03 and 04, we can close this issue.
