### ISSUE TITLE
Testgrid cannot run apim-test-integration tests

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#745]
**Description:**

The apim-test-integration repo does not contain scenario.sh/run-scenario.sh file. Because of that reason, testgrid cannot run API-M tests.

**Possible solutions:**
1. If a run-scenario.sh file is missing, testgrid should run the [default jmeter.sh command](https://github.com/wso2-incubator/identity-test-integration/blob/master/scenario01/scenario.sh#L17).
2. As a short-term measure, introduce run-scenario.sh scripts into apim-test-integration.

**Affected Product Version:**
0.9.0-m25

**OS, DB, other environment details and versions:**    
apim-test-integration
ei-test-integration

**Related Issues:**

**Comment by pasindujw** [comment]
@kasunbg APIM scenario directories (most of them) contain two scripts as base-setup.sh and teardown.sh. 
In addition to that there more than one JMeter scripts in some of the scenarios. 
Isn't it possible to enforce to have a default script (like run-scenario.sh) in each scenario and arrange the order of the scripts in it?
Otherwise, one option would be;
The jms files have names as "01-Scenario-1-...." , "01-pre-scenario-...", "01-post-scenario"....
We can arrange the order by the number in the name and 'pre', 'post' tags.
But once again we are enforcing a rule. So I think enforcing a new script would be more clean.

WDYT?

**Comment by kasunbg** [comment]
HI @pasindujw ,

Testgrid now has support to execute a init script and a teardown script.

If a scenario has more than one jmeter script, then we run them according to the alphabetical order. See [scenario02](https://github.com/wso2/identity-test-integration/tree/master/scenario02/jmeter) of IS for example. Numbering the jmx files is that approach we have taken already for IS. After that, @harshanL made jmeter scripts to run outside of testgrid.

With that, what you have is a _run-scenario.sh_ that takes care of all the underlying jmeter jmx files. See:
https://github.com/wso2/identity-test-integration/blob/master/scenario22/run-scenario.sh

Is this what's proposed here? :)

Thanks,
KasunG

**Comment by pasindujw** [comment]
As per the offline discussion with Kasun, the following will be implemented;
1. If run-scenario is available: Follow its order.
2. If run-scenario is not provided:  Create a run-scenario by getting scripts order based on the file names.

Thanks.
